spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tNZ13GYLaHfBnZVHvn1
      secret-key: ybVlTXf7Oc3cMv6L2oeEXUqqOOiyCK
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-shiqchen
  application:
    name: gulimall-third-party



server:
  port: 30000